# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [20]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?
import numpy as np
lista = list(range(1000000))
arraynp = np.arange(1000000)
%time lista * 2
%time arraynp * 2


Wall time: 16 ms
Wall time: 2.02 ms


array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

### Exercício 2

In [23]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0
import numpy as np
array10 = np.arange(10)
print(array10)
array10[5:9] = 0
print(array10)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 0 0 0 0 9]


### Exercício 3

In [64]:
# Crie um array de 3 dimensões e imprima a dimensão 1 
array3d = np.arange(24).reshape(2,3,4)
print(array3d)
array3d[0]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Exercício 4

In [96]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
arr2d = np.arange(9).reshape(3,3) + 1
print(arr2d)
print('--terceira linha da matriz-- \n', arr2d[2])
print(arr2d[:2,  1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--terceira linha da matriz-- 
 [7 8 9]
[[2 3]
 [5 6]]


### Exercício 5

In [98]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
print(arr)
print('--transposta -- \n', arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
--transposta -- 
 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


### Exercício 6

In [106]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
for x, y, c in zip(xarr, yarr, cond):
    print(x,y,c)
[x if c else y for x, y, c in zip(xarr, yarr, cond)] 

1.1 2.1 True
1.2 2.2 False
1.3 2.3 True
1.4 2.4 True
1.5 2.5 False


[1.1, 2.2, 1.3, 1.4, 2.5]

### Exercício 7

In [110]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B
A = np.arange(10)
print(A)
np.save('file_arr', A)

B = np.load('file_arr.npy')
print(B)  

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


### Exercício 8

In [113]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [117]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [125]:
data = resp.json()
data[0]['title']
import pandas as pd
df = pd.DataFrame(data, columns=['number','title','labels','state'])
df.head()

number                                              title  \
0   28665  Odd error message, concerning numpy using an a...   
1   28664  pct_change with frequency set as 'BM' throws v...   
2   28663                   to_html()没有encoding参数？造成输出中文显示乱码   
3   28662                             BUG: Fix groupby.apply   
4   28661                  PERF: Make matplotlib import lazy   

                                              labels state  
0                                                 []  open  
1                                                 []  open  
2  [{'id': 47229171, 'node_id': 'MDU6TGFiZWw0NzIy...  open  
3  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
4  [{'id': 527603109, 'node_id': 'MDU6TGFiZWw1Mjc...  open

### Exercício 10

In [126]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas
import sqlite3
import pandas as pd
query = """
CREATE TABLE TESTE
(Cidade VARCHAR(20), 
 Estado VARCHAR(20),
 taxa REAL,        
 Impostos INTEGER
);"""
con = sqlite3.connect('dsa.db')
con.execute(query)
con.commit()

In [127]:
data = [('Natal', 'Rio Grande do Norte', 1.25, 6),
        ('Recife', 'Pernambuco', 2.6, 3),
        ('Londrina', 'Paraná', 1.7, 5)]
stmt = "INSERT INTO TESTE VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)
con.commit()

In [128]:
cursor = con.execute('select * from teste')
rows = cursor.fetchall()
rows

[('Natal', 'Rio Grande do Norte', 1.25, 6),
 ('Recife', 'Pernambuco', 2.6, 3),
 ('Londrina', 'Paraná', 1.7, 5)]

In [129]:
cursor.description

(('Cidade', None, None, None, None, None, None),
 ('Estado', None, None, None, None, None, None),
 ('taxa', None, None, None, None, None, None),
 ('Impostos', None, None, None, None, None, None))

In [130]:
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

Cidade               Estado  taxa  Impostos
0     Natal  Rio Grande do Norte  1.25         6
1    Recife           Pernambuco  2.60         3
2  Londrina               Paraná  1.70         5

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>